#!/bin/sh
# /etc/init.d/piratebox

### BEGIN INIT INFO
# Provides:          piratebox
# Required-Start:    $all
# Required-Stop:     $network $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      6 1 0
# Short-Description: All services around piratebox
# Description:       Based on /opt/piratebox/conf/piratebox.conf starts:  * DNSMASQ * HOSTAPD * DROOPY * WLAN-config * CHAT
### END INIT INFO

###
#  Default start-stop script for piratebox services on a laptop
#   written by Matthias Strubel  (matthias.strubel@aod-rpg.de) 2011-02-22
#  licenced by gpl, feel free to improve and send me comments


[ -f /etc/default/rcS ] && . /etc/default/rcS

# PATH for /opt piratebox folder
PATH=$PATH:/opt/piratebox/bin




PIDFILE_SHOUTBOX=/opt/piratebox/tmp/shoutbox_daemon.pid


PIRATEBOX=/opt/piratebox
CONF=$PIRATEBOX/conf/piratebox.conf


export PYTHONPATH=:$PYTHONPATH:$PIRATEBOX_PYTHONPATH

if [ -f $CONF ] ; then
   . $CONF
else
   echo "Configuration file not found"
   exit 1
fi

#If you can't find this file
if [[ -f $PIRATEBOX/conf/init_done ]] ; then
   INIT=OK
else
   $PIRATEBOX/bin/hooks/hook_pre_init.sh  "$CONF"
   $PIRATEBOX/bin/install_piratebox.sh "$CONF" modules   
   $PIRATEBOX/bin/install_piratebox.sh "$CONF" part2
   $PIRATEBOX/bin/hooks/hook_post_init.sh  "$CONF"
   touch   $PIRATEBOX/conf/init_done
fi

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script piratebox "

    # Generate hosts & dnsmasq file
    $PIRATEBOX/bin/generate_config_files.sh  "$CONF"

    $PIRATEBOX/bin/hooks/hook_piratebox_start.sh  "$CONF"


    if [ "$PBX_JSON_GENERATION" = "yes" ]; then
        $PIRATEBOX_FOLDER/bin/json_generation.sh  $CONF
    fi

    if [ "$DO_IW" = "yes" ] ; then
       log_daemon_msg " Setting up Interface (iw) "
       iw $PHY_IF interface add $INTERFACE type managed
    fi

    if [ "$PROBE_INTERFACE" = "yes" ] ; then
      echo "  Probe wlan"
      #Setting up WLAN Interface
      piratebox_setup_wlan.sh  $CONF probe
    fi
     if  [ $? -ne 0 ] ;  then
       echo "failed probing Interface"
     else


       if [ "$DO_IFCONFIG" = "yes" ] ; then
         echo "  Setting up wlan"
         #Setting up WLAN Interface
         piratebox_setup_wlan.sh  $CONF start
         if  [ $? -ne 0 ] ;  then
          echo "failed setting up Interface"
          exit 255
         fi
      fi
      #BRIDGE
      if [ "$DO_BRIDGE" = "yes" ] ; then
         echo "Adding $INTERFACE to bridge $BRIDGE //  brctl addif $BRIDGE  $INTERFACE "
         sleep 1
         BR_CMD="brctl addif  $BRIDGE  $INTERFACE"
         ( $BR_CMD ; )
         if  [ $? -ne 0 ] ;  then
           echo "failed :( "
         fi
      fi


       #Do shoutbox stuff
       $PIRATEBOX/bin/shoutbox_stuff.sh $WWW_FOLDER $CONF




       #Start Global Chat daemon if needed.
       if [ "$GLOBAL_CHAT" = "yes" ] ; then
          echo  "Starting global chat service..."
          start-stop-daemon -S -m -b -p $PIDFILE_SHOUTBOX  -x $PIRATEBOX/bin/shoutbox_daemon.sh -- $CONF
          echo $?
       fi 

     fi

      $PIRATEBOX/bin/hooks/hook_piratebox_start_done.sh  "$CONF"

    ;;
  stop)
    echo  "Stopping script piratebox"

    $PIRATEBOX/bin/hooks/hook_piratebox_stop.sh  "$CONF"



    #Start Global Chat daemon if needed.
    if [ "$GLOBAL_CHAT" = "yes" ] ; then
        echo  "Stopping global chat service..."
        start-stop-daemon -K  -q -p $PIDFILE_SHOUTBOX
        echo $?
    fi



     if [ "$DO_IFCONFIG" = "yes" ] ; then
       piratebox_setup_wlan.sh $CONF stop
     fi

     if [ "$DO_IW" = "yes" ] ; then
       iw dev $INTERFACE del
     fi

      #BRIDGE
      if [ "$DO_BRIDGE" = "yes" ] ; then
         echo "Remove  $INTERFACE to bridge $BRIDGE //  brctl addif
$BRIDGE  $INTERFACE "
         sleep 1
         BR_CMD="brctl delif  $BRIDGE  $INTERFACE"
         ( $BR_CMD ; )
         if  [ $? -ne 0 ] ;  then
           echo "failed :( "
         fi
      fi

      $PIRATEBOX/bin/hooks/hook_piratebox_stop_done.sh  "$CONF"
    ;;
  *)
    echo "Usage: /etc/init.d/piratebox {start|stop}"
    exit 1
    ;;
esac

exit 0
