#!/bin/sh

MODULE_LIST="$MODULE_LIST custom_dirlist"

custom_dirlist_myself="custom_dirlist"
custom_dirlist_start_order=13
custom_dirlist_stop_order=99
custom_dirlist_needed_config=" "
custom_dirlist_crucial="no"

func_custom_dirlist_start(){
       #Start here the custom_dirlist i.e.
	$PIRATEBOX_FOLDER/bin/distribute_files.sh "$SHARE_FOLDER/Shared"
       local RC=$?
       _check_rc_  "$custom_dirlist_myself"  "$RC"  "$custom_dirlist_crucial" 
       return   $RC
}

func_custom_dirlist_stop(){
       _check_rc_ "$custom_dirlist_myself"  "0"
       return   $RC
}

func_custom_dirlist_get_config(){
	echo $custom_dirlist_needed_config
}
func_custom_dirlist_get_start_order(){
	echo $custom_dirlist_start_order
}
func_custom_dirlist_get_stop_order(){
	echo $custom_dirlist_stop_order
}