#!/bin/sh

MODULE_LIST="$MODULE_LIST example"

example_myself="example"
example_start_order=99
example_stop_order=01
example_needed_config="00_hostname.conf"
example_crucial="no"

func_example_start(){
       #Start here the example i.e.
       echo "Hello World... ${HOSTNAME}"

       local RC=$?
       echo $RC
       return  $RC
}

func_example_stop(){
	echo "Stopping Example..."
    	
       local RC=$?
       echo $RC
       return  $RC
}

func_example_get_config(){
	echo $example_needed_config
}
func_example_get_start_order(){
	echo $example_start_order
}
func_example_get_stop_order(){
	echo $example_stop_order
}