#!/bin/sh

MODULE_LIST="$MODULE_LIST lighttpd"

lighttpd_myself="lighttpd"
lighttpd_start_order=30
lighttpd_stop_order=10
lighttpd_needed_config="lighttpd.conf"
lighttpd_crucial="no"

func_lighttpd_start(){
       #Start here the lighttpd i.e.
       start-stop-daemon -S -q  -p $LIGHTTPD_PIDFILE -x /usr/sbin/lighttpd -- -f $LIGHTTPD_CONF
       local RC=$?
       return  _check_rc_ "$lighttpd_myself"  "$lighttpd_crucial" 
}

func_lighttpd_stop(){
    	start-stop-daemon -K -q -p $LIGHTTPD_PIDFILE
       local RC=$?
       return    _check_rc_ "$lighttpd_myself"  "$RC"
}

func_lighttpd_get_config(){
	echo $lighttpd_needed_config
}